name: Build Frontend

on: []

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build with Node "${{ matrix.node-version }}"
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      run: |
          npm install
          npm run build --if-present
    - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build_node_${{ matrix.node-version }}
          path: |
            build
            !build/**/*.md