name: Build Frontend

on: 
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install dependencies 
      run: |
        npm ci --production
    - name: Build Frontend
      run: |
          npm run build --if-present
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nextparty_truth_or_dare_frontend
        path: |
          build
