name: Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: install dependencies
        run: npm i
        
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start:cc
          
      - name: run cli tests
        run: npm run cypress:run
        
      - name: generate report
        run: npm run cc:report
        
      - name: Archive report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: /coverage/Icov-report/index.html
      
        
      
  

