name: Mirror

on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    
    #goto repository
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
          
     #mirror to repo   
      - uses: spyoungtech/mirror-action@master
        with:
          REMOTE: ${{ secrets.GIT_MIRROR_REPO }}
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          GIT_SSH_NO_VERIFY_HOST: "true"