name: Mirror

on: [push, pull_request]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    
    #goto repository
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
          
     #mirror to gitlab     
      - uses: spyoungtech/mirror-action@master
        with:
          REMOTE: "https://gitlab.mi.hdm-stuttgart.de/mwa/ws21/wop.git"
          GIT_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
